services:


  # -------------------------------
  # Flask Backend
  # -------------------------------
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voting-flask-api
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./backend/encodings:/app/encodings
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - voting-net

  # -------------------------------
  # PostgreSQL Database
  # -------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: voting-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: voting123
      POSTGRES_DB: votingdb
    ports:
      - "5432:5432"
    networks:
      - voting-net

  # -------------------------------
  # Node Voting Core
  # -------------------------------
  voting-core:

    build:
      context: .
      dockerfile: voting-core/Dockerfile
    container_name: voting-core-api
    restart: unless-stopped
    env_file:
      - ./voting-core/.env
    ports:
      - "3001:3001"
    networks:
      - voting-net

  # -------------------------------
  # React Frontend
  # -------------------------------
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: voting-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - flask-backend
      - voting-core
    networks:
      - voting-net

  # -------------------------------
  # NGINX Reverse Proxy
  # -------------------------------
  nginx:
    image: nginx:1.25-alpine
    container_name: voting-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./devops/ssl/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - flask-backend
      - voting-core
    networks:
      - voting-net


# -------------------------------
# Network
# -------------------------------
networks:
  voting-net:
    driver: bridge



